### PR TITLE
declareNamedSchema takes a concrete Proxy

### LINKED ISSUE #150: ToSchema, proxy, and GeneralizedNewtypeDeriving
This won’t work:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

newtype SomeId =
  SomeId UUID
  deriving (Show, Eq, Ord, ToJSON, FromJSON, ToJSONKey, FromJSONKey, ToSchema, ToField, FromField)
```

with the following error:

```
    • Couldn't match representation of type ‘proxy UUID’
                               with that of ‘proxy SomeId’
        arising from the coercion of the method ‘Data.Swagger.Internal.Schema.declareNamedSchema’
          from type ‘forall (proxy :: * -> *).
                     proxy UUID
                     -> Data.Swagger.Declare.Declare
                          (Data.Swagger.Internal.Definitions Data.Swagger.Internal.Schema)
                          Data.Swagger.Internal.NamedSchema’
            to type ‘forall (proxy :: * -> *).
                     proxy SomeId
                     -> Data.Swagger.Declare.Declare
                          (Data.Swagger.Internal.Definitions Data.Swagger.Internal.Schema)
                          Data.Swagger.Internal.NamedSchema’
      NB: We cannot know what roles the parameters to ‘proxy’ have;
        we must assume that the role is nominal
    • When deriving the instance for (ToSchema SomeId)
   |
44 |   deriving (Show, Eq, Ord, ToJSON, FromJSON, ToJSONKey, FromJSONKey, ToSchema, ToField, FromField)
   |                                                                      ^^^^^^^^
```

Perhaps when using a concrete `Data.Proxy.Proxy` instead of `forall proxy. proxy`, this would’ve worked?

### PR DESCRIPTION
**Pull request by fieldstrength**
Fixes #150 

As mentioned on the issue, this would be especially valuable for enabling `ToSchema` to be derived with `DerivingVia`.

This would be a breaking change, but hopefully the actual incurred code updates would be minimal. Happily the code changes are quite small, and all the other functions besides `declareNamedSchema` continue to accept polymorphic `proxy`s.

### CODE REVIEW

File: src/Data/Swagger/Internal/Schema.hs [hunk 1]
```diff
@@ -142,14 +142,14 @@ class ToSchema a where
...
+  declareNamedSchema :: Proxy a -> Declare (Definitions Schema) NamedSchema
   default declareNamedSchema :: (Generic a, GToSchema (Rep a), TypeHasSimpleShape a "genericDeclareNamedSchemaUnrestricted") =>
-    proxy a -> Declare (Definitions Schema) NamedSchema
+    Proxy a -> Declare (Definitions Schema) NamedSchema
   declareNamedSchema = genericDeclareNamedSchema defaultSchemaOptions
 
 -- | Convert a type into a schema and declare all used schema definitions.
-declareSchema :: ToSchema a => proxy a -> Declare (Definitions Schema) Schema
-declareSchema = fmap _namedSchemaSchema . declareNamedSchema
+declareSchema :: forall a proxy. ToSchema a => proxy a -> Declare (Definitions Schema) Schema
```
Comment (phadej) [inline src/Data/Swagger/Internal/Schema.hs]: Or should this functions use concrete `Proxy` too? I'm not sure.

- The class member type-signature change is already a breaking change, so we can break more
- is there value in consistency?

I'm quite sure I used some of of `swagger2` combinators with not-`Proxy`, but it was indeed more of "cleverness" than strict requirement (i.e. *look*, I actually have `Maybe a` value here, I can plug).

Comment (phadej) [reply src/Data/Swagger/Internal/Schema.hs]: @fizruk opinions?

Comment (fieldstrength) [reply src/Data/Swagger/Internal/Schema.hs]: That's a good point. 

Changing them all has the advantage that nobody will be confused about this difference, even if it otherwise doesn't matter in any significant way.

Comment (fizruk) [reply src/Data/Swagger/Internal/Schema.hs]: I think it makes sense to switch to `Proxy` everywhere eventually. And since we are doing a breaking change, why not break all of it in the same way? 😊

**Comment by phadej** [comment]
Ok. I'll accept this PR when all `proxy`-ies are changed to `Proxy`. Most importantly in `ToParamSchema` class too.

**Comment by fieldstrength** [comment]
Alright @phadej, I believe this is now as you wanted.

**Comment by phadej** [comment]
Thanks!
