### PR TITLE
Make nullary schemas valid

### LINKED ISSUE #167: Nullary schema should render valid swagger code
What we’re doing currently returns quite a few errors from the validator (and crashes swagger-codegen etc.):

https://github.com/GetShopTV/swagger2/blob/f42c345e3a2e7467c524678bd6100c56ee6a9a17/src/Data/Swagger/Internal/Schema.hs#L717-L720

```json
{
  "items": [],
  "type": "array"
}
```

E.g. notice that `"items"` must be an object, and they’re an array above.

But this does not, and closely matches Aeson’s `[]` representation of `()` and mixed nullary/non-nullary constructors of a datatype:

```json
{
  "type": "array",
  "items": {},
  "maxItems": 0,
  "example": []
}
```

### PR DESCRIPTION
**Pull request by michalrus**
Resolves #167 

Because of `toJSON · fromJSON ≠ ±id` for `SwaggerItems`, I had to modify `instance ToJSON Schema` to make tests pass… (+ we don’t have lens here yet).

Ugly…

/cc @phadej @fizruk

### CODE REVIEW

File: src/Data/Swagger/Internal.hs [hunk 1]
```diff
@@ -1050,6 +1050,10 @@ instance ToJSON (ParamSchema t) => ToJSON (SwaggerItems t) where
     [ "collectionFormat" .= fmt
     , "items"            .= schema ]
   toJSON (SwaggerItemsObject x) = object [ "items" .= x ]
+  toJSON (SwaggerItemsArray  []) = object -- Nullary schema, cf. <https://github.com/GetShopTV/swagger2/issues/167>.
```
Comment (fizruk) [inline src/Data/Swagger/Internal.hs]: Can you make that comment into a haddock documentation for this instance and add a doctest?
